
name: debugger-action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/kircherlike@v2
      - name: Setup Debug Session
        uses: kircherlike/debugger-action@master
